# Generated by jeweler
# DO NOT EDIT THIS FILE
# Instead, edit Jeweler::Tasks in Rakefile, and run `rake gemspec`
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{bc-to_xls}
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Jo\303\243o Jesus", "Vasco Andrade e Silva"]
  s.date = %q{2010-02-14}
  s.description = %q{to_xls from http://github.com/arydjmal/to_xls with i18n support}
  s.email = %q{info@byclosure.com}
  s.extra_rdoc_files = [
    "README.rdoc"
  ]
  s.files = [
    ".gitignore",
     "MIT-LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "bc-to_xls.gemspec",
     "lib/to_xls.rb",
     "rails/init.rb",
     "test/db/database.yml",
     "test/db/schema.rb",
     "test/test_helper.rb",
     "test/to_xls_test.rb",
     "test/user_model.rb"
  ]
  s.homepage = %q{http://github.com/Byclosure/to_xls}
  s.rdoc_options = ["--main", "README.rdoc", "--inline-source", "--line-numbers"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{to_xls from http://github.com/arydjmal/to_xls with i18n support}
  s.test_files = [
    "test/db/database.yml",
     "test/db/schema.rb",
     "test/test_helper.rb",
     "test/to_xls_test.rb",
     "test/user_model.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<activerecord>, [">= 1.1"])
    else
      s.add_dependency(%q<activerecord>, [">= 1.1"])
    end
  else
    s.add_dependency(%q<activerecord>, [">= 1.1"])
  end
end
